# Generated by Django 4.2.4 on 2026-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('CRB', 'Core Rule Book'), ('SPB', 'Splat Book'), ('SB', 'Setting Book'), ('CB', 'Campaign Book'), ('MOD', 'Module')], default='CRB', max_length=3),
        ),
    ]
