# Generated by Django 4.2.4 on 2026-09-20 11:25

from django.db import migrations, models
import file_validator.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_authors_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', validators=[file_validator.models.DjangoFileValidator(acceptable_mimes=['image/png', 'image/jpeg', 'image/jpg', 'image/webp'], acceptable_types=['image'], libraries=['python_magic', 'filetype'], max_upload_file_size=5242880)]),
        ),
    ]
