# Generated by Django 4.2.4 on 2026-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('CRB', 'Core Rule Book'), ('STS', 'Starter Set'), ('SPB', 'Splat Book'), ('SB', 'Setting Book'), ('CB', 'Campaign Book'), ('MOD', 'Module')], default='CRB', max_length=3),
        ),
    ]
