# Generated by Django 4.2.4 on 2026-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('CRB', 'Core Rule Book'), ('STS', 'Starter Set'), ('SPB', 'Splat Book'), ('SB', 'Setting Book'), ('CB', 'Campaign Book'), ('MOD', 'Module'), ('BES', 'Bestiary')], default='CRB', max_length=3),
        ),
    ]
